sudo: required
services: 
  - docker

before_install: 
  - docker build -t thetkpark/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run thetkpark/react-test npm test -- --coverage

after_success: 
  #Build docker image
  - docker build -t thetkpark/multi-client ./client
  - docker build -t thetkpark/multi-nginx ./nginx
  - docker build -t thetkpark/multi-server ./server
  - docker build -t thetkpark/multi-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these image and push to docker hub
  - docker push thetkpark/multi-client
  - docker push thetkpark/multi-nginx
  - docker push thetkpark/multi-server
  - docker push thetkpark/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker 
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-458140489083
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY


